export const site = {
  name: "Rajlav Technologies",
  alternateName: "Rajlav Anitech",
  domain: "https://anitech.rajlav.co.in",
  description:
    "Rajlav Technologies designs and builds custom software, AI solutions, web and mobile applications, SaaS platforms, and business automation systems for modern businesses.",
  shortDescription:
    "AI, software, web, mobile, SaaS and business automation solutions for startups and enterprises.",
  email: "hello@anitech.rajlav.co.in",
  phone: "+91 62058 34086",
  city: "Noida",
  region: "Uttar Pradesh",
  country: "India",
  linkedIn: "https://www.linkedin.com/company/rajlav-anitech/posts/?feedView=all",
};

export const services = [
  {
    slug: "ai-development",
    title: "AI Development Services in Noida",
    navTitle: "AI Development",
    meta: "AI development services in Noida for automation, LLM integrations, analytics, chatbots and intelligent business workflows.",
    summary:
      "Build AI applications, assistants, intelligent workflows and automation systems that solve real business problems.",
    mobileSummary: "AI applications, assistants and intelligent automation.",
    sections: [
      "We build AI assistants, retrieval systems, chatbot workflows, document automation and predictive dashboards for teams that need faster decisions.",
      "Every AI project starts with business goals, available data, integration needs and risk review before production planning begins.",
      "Rajlav Technologies supports businesses in Noida, Delhi NCR and remote markets with AI strategy, software engineering and ongoing optimization.",
    ],
  },
  {
    slug: "software-development",
    title: "Custom Software Development Company in Noida",
    navTitle: "Software Development",
    meta: "Custom software development company in Noida building secure business applications, dashboards, portals and scalable digital products.",
    summary:
      "Purpose-built software for businesses that need more flexibility than off-the-shelf tools can provide.",
    mobileSummary: "Business software built around your workflow.",
    sections: [
      "We plan, design and develop custom software for startups, educational platforms, healthcare providers, finance teams and enterprises.",
      "Our team focuses on maintainable architecture, role-based access, clean data flows, APIs, testing and deployment support.",
      "We can build new products from scratch or modernize older tools when manual work and disconnected systems begin slowing growth.",
    ],
  },
  {
    slug: "web-development",
    title: "Web Development Company in Noida",
    navTitle: "Web Development",
    meta: "Web development company in Noida creating SEO-friendly websites, web applications, portals and conversion-focused digital experiences.",
    summary:
      "Fast, responsive and scalable websites, web applications, dashboards and business platforms.",
    mobileSummary: "Modern websites and web applications.",
    sections: [
      "Our web development services cover business websites, landing pages, web applications, customer portals, admin dashboards and API integrations.",
      "We implement clean HTML, metadata, structured data, image optimization, mobile-first layouts and performance-minded frontend engineering.",
      "Rajlav Technologies connects websites to lead forms, analytics, CRM workflows, payment systems and business automation tools.",
    ],
  },
  {
    slug: "mobile-app-development",
    title: "Mobile App Development Company in Noida",
    navTitle: "Mobile App Development",
    meta: "Mobile app development company in Noida building Android, iOS and cross-platform apps for startups and business workflows.",
    summary:
      "User-friendly Android and iOS applications designed around your customers and business workflows.",
    mobileSummary: "Android and iOS apps for your customers.",
    sections: [
      "We build customer apps, internal apps, learning apps, healthcare workflows, finance tools and mobile dashboards.",
      "Projects can include UX planning, authentication, notifications, offline-ready workflows, API integration, testing and deployment support.",
      "We help founders and companies choose between native, cross-platform and progressive web app approaches based on product needs.",
    ],
  },
  {
    slug: "saas-development",
    title: "SaaS Development Company in Noida",
    navTitle: "SaaS Development",
    meta: "SaaS development company in Noida building subscription platforms, multi-user products, dashboards and scalable cloud software.",
    summary:
      "Multi-user, subscription-based software platforms built for recurring revenue and long-term scalability.",
    mobileSummary: "Scalable subscription-based software platforms.",
    sections: [
      "We plan tenant structure, permissions, onboarding, admin controls, billing readiness and support workflows early in SaaS projects.",
      "Rajlav Technologies builds MVPs, improves existing SaaS products and creates internal platforms that can grow into commercial software.",
      "We keep architecture practical so startups can launch quickly while leaving room for security, reporting and future scale.",
    ],
  },
  {
    slug: "business-automation",
    title: "Business Automation Company in Noida",
    navTitle: "Business Automation",
    meta: "Business automation company in Noida creating workflow automation, reporting systems, AI assistants and integrated business tools.",
    summary:
      "Connect tools, automate repetitive processes and reduce manual work across your organization.",
    mobileSummary: "Automate repetitive processes and connect your tools.",
    sections: [
      "Automation work often includes CRM workflows, lead routing, reporting, document processing, inventory updates and payment records.",
      "We map the existing process first, then build software that reduces manual work without hiding important business controls.",
      "Rajlav Technologies serves Noida and Delhi NCR businesses that need leaner operations, faster reporting and fewer disconnected tools.",
    ],
  },
  {
    slug: "fintech-development",
    title: "FinTech Software Development Company",
    navTitle: "FinTech Development",
    meta: "FinTech software development for CRMs, loan workflows, payment systems, dashboards and secure finance business applications.",
    summary:
      "Custom platforms for finance, CRM, loan workflows, payments, customer management and financial operations.",
    mobileSummary: "Finance, CRM, payments and loan management systems.",
    sections: [
      "FinTech software can include loan management, customer portals, payment reconciliation, financial dashboards and approval workflows.",
      "We focus on clear records, reliable integrations, role-based access and audit-friendly behavior.",
      "Our team supports finance startups and service businesses that need custom software beyond generic off-the-shelf tools.",
    ],
  },
  {
    slug: "healthcare-software",
    title: "Healthcare Software Development Company",
    navTitle: "Healthcare Software",
    meta: "Healthcare software development for management systems, patient workflows, dashboards and secure healthcare technology platforms.",
    summary:
      "Healthcare management systems, appointment workflows, dashboards and administrative automation for providers.",
    mobileSummary: "Healthcare workflows, records and operations software.",
    sections: [
      "Healthcare software requires simple interfaces, responsible data handling and dependable workflows for busy staff.",
      "We develop healthcare management systems, appointment flows, dashboards, communication tools and administrative automation.",
      "When sensitive data is involved, we plan access control, logs and secure handling from the start.",
    ],
  },
  {
    slug: "edtech-development",
    title: "EdTech Software Development Company",
    navTitle: "EdTech Development",
    meta: "EdTech software development for learning platforms, LMS features, student dashboards, content workflows and education apps.",
    summary:
      "Learning platforms, course management systems, student dashboards, assessments and digital education products.",
    mobileSummary: "Learning platforms and education technology.",
    sections: [
      "EdTech projects can include course platforms, assessments, video learning, mobile learning and admin portals.",
      "We balance learner experience with educator workflows so the platform is useful for both sides of the classroom.",
      "Rajlav Technologies supports MVP builds, platform modernization and custom learning features for education businesses.",
    ],
  },
];

export const portfolio = [
  {
    slug: "rajlav-edutech",
    title: "Rajlav Edutech - Digital Learning Platform",
    category: "EdTech",
    industry: "Education Technology",
    thumbnail: "/rajlav-edutech-learning-platform.svg",
    alt: "Rajlav Edutech digital learning platform branded project cover",
    description: "A digital learning platform designed for courses, educational content, student learning and online education.",
    mobileDescription: "Digital learning platform for courses, content and online education.",
    tags: ["EdTech", "Web", "Learning Platform"],
    services: ["edtech-development", "software-development"],
    isRealProject: true,
    overview: "Rajlav Edutech is a Rajlav ecosystem education platform focused on digital learning, course content and online education experiences.",
    problem: "Education products need clear content structure, smooth learner access and a platform foundation that can support learning workflows without feeling complicated.",
    solution: "The platform is designed around course discovery, educational content delivery and student learning journeys.",
    features: ["Course and educational content structure", "Student learning experience", "Online education platform foundation"],
    technology: ["Web Platform", "Digital Learning", "Responsive UI"],
    approach: "The product direction focuses on simple navigation, clear content hierarchy and a scalable platform structure for education use cases.",
    outcome: "Designed for scalable digital learning within the Rajlav ecosystem.",
  },
  {
    slug: "rajlav-finance",
    title: "Rajlav Finance - Digital Finance Platform",
    category: "FinTech",
    industry: "Financial Services",
    thumbnail: "/rajlav-finance-platform.svg",
    alt: "Rajlav Finance digital finance platform branded project cover",
    description: "A finance-focused digital platform for customer enquiries, financial services and streamlined business workflows.",
    mobileDescription: "Finance platform for enquiries, services and business workflows.",
    tags: ["FinTech", "Web", "Business Workflows"],
    services: ["fintech-development", "saas-development"],
    isRealProject: true,
    overview: "Rajlav Finance is a Rajlav ecosystem digital finance platform focused on customer enquiries, financial service communication and business workflow support.",
    problem: "Finance-facing businesses need a trustworthy digital presence and clear enquiry flow without overstating product features that may not exist yet.",
    solution: "The platform presents financial services clearly and supports customer enquiry workflows for business follow-up.",
    features: ["Financial service presentation", "Customer enquiry workflow", "Business communication foundation"],
    technology: ["Web Platform", "Financial Services", "Responsive UI"],
    approach: "The project prioritizes clarity, credibility and clean enquiry paths for users exploring finance-related services.",
    outcome: "Designed to support digital finance enquiries and streamline business communication.",
  },
  {
    slug: "easyhome",
    title: "EasyHome - Property & Booking Platform",
    category: "Real Estate Technology",
    industry: "Real Estate",
    thumbnail: "/easyhome-property-platform.svg",
    alt: "EasyHome property booking platform branded project cover",
    description: "A property technology platform designed for property discovery, availability, bookings, payments and property management workflows.",
    mobileDescription: "Property platform for discovery, bookings and management workflows.",
    tags: ["Real Estate", "Bookings", "Property Tech"],
    services: ["web-development", "software-development"],
    isRealProject: true,
    overview: "EasyHome is a property technology platform connected with the Rajlav ecosystem and designed around property discovery and booking workflows.",
    problem: "Property businesses need a digital system that can organize listings, availability, booking interest and property operations in one user-friendly experience.",
    solution: "The platform is designed to support property discovery, availability checks, booking flows, payments and property management workflows.",
    features: ["Property discovery", "Availability and booking workflows", "Payment and property management support"],
    technology: ["Property Tech", "Web Platform", "Booking Workflows"],
    approach: "The product direction focuses on clear listing journeys, practical booking steps and operational workflows for property management.",
    outcome: "Built around property booking workflows and digital property operations.",
  },
  {
    slug: "rajlav-pro-tool-kit",
    title: "Rajlav Pro Tool Kit",
    category: "Developer Tools",
    industry: "Productivity Tools",
    thumbnail: "/rajlav-pro-toolkit-dashboard.svg",
    alt: "Rajlav Pro Tool Kit branded project cover",
    description: "A professional toolkit designed to improve creative and development workflows with integrated productivity features.",
    mobileDescription: "Professional toolkit for creative and development workflows.",
    tags: ["Developer Tools", "Productivity", "Workflow"],
    services: ["software-development", "business-automation"],
    isRealProject: true,
    overview: "Rajlav Pro Tool Kit is a Rajlav ecosystem toolkit focused on improving creative and development workflows.",
    problem: "Creative and development work often depends on repeated small tasks, tool switching and workflow friction.",
    solution: "The toolkit is designed as a professional productivity layer for integrated creative and development workflows.",
    features: ["Workflow productivity tools", "Creative and development support", "Integrated toolkit experience"],
    technology: ["Developer Tools", "Productivity", "Workflow Software"],
    approach: "The product direction focuses on practical utilities, fast access and clean organization for professional workflows.",
    outcome: "Designed to improve creative and development productivity within the Rajlav ecosystem.",
  },
];

export const faqs = [
  ["What does Rajlav Technologies do?", "Rajlav Technologies builds custom software, AI solutions, web and mobile applications, SaaS platforms and business automation systems."],
  ["Can you build custom software?", "Yes. We can take a product from requirements and UI/UX through development, testing, deployment and future improvements."],
  ["Do you work with startups?", "Yes. We work with startups and growing businesses that need technology to validate, launch and scale their products."],
  ["Can you integrate AI into an existing product?", "Yes. AI capabilities can be integrated into existing applications depending on the product, data and business requirements."],
  ["Do you build SaaS platforms?", "Yes. We can develop SaaS products with user management, subscriptions, dashboards, APIs, integrations and scalable backend infrastructure."],
  ["Do you provide ongoing support?", "Yes. Ongoing maintenance, improvements, feature development and technical support can be provided depending on the project requirements."],
  ["Where does Rajlav Technologies operate?", "Rajlav Technologies is based in Noida, Uttar Pradesh and works with businesses in Delhi NCR and clients beyond the region."],
];

export const url = (path = "") => `${site.domain}${path}`;
