kind = "web"
previewPath = "/"
title = "Rajlav Animation"
version = "1.0.0"
id = "artifacts/rajlav-animation"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22722

[services.development]
run = "pnpm --filter @workspace/rajlav-animation run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/rajlav-animation", "run", "build" ]
publicDir = "artifacts/rajlav-animation/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22722"
BASE_PATH = "/"
